### ISSUE TITLE
Hats off to you man! (Not an issue)

### ISSUE THREAD

**Issue by ghost** [CCobaltDev/SScript-Archive#10]
Thanks for helping everyone use SScript now that it is no longer hosted by haxelib. I hate it when the developers of regularly use dependencies just disappear without an archive or 3rd party of it. I get that some people do that stuff with reasons behind it but it still makes me mad. Anyways 👏 👏 👏 👏 👏 👏 👏 👏 👏 .

**Comment by tposejank** [comment]
thx
