### ISSUE TITLE
Error: Failed with error: No such Project : SScript-7,7,0.zip

### ISSUE THREAD

**Issue by ghost** [CCobaltDev/SScript-Archive#12]
![Снимок экрана 2024-10-07 151319](https://github.com/user-attachments/assets/c459dbfe-4860-485a-a723-2584cef7ae1d)
why error is the worst please help

**Comment by tposejank** [comment]
More information please

**Comment by ghost** [comment]
please link youtube

**Comment by tposejank** [comment]
??? No? You have clear instructions in the Readme.

**Comment by ghost** [comment]
![Снимок экрана 2024-10-07 174641](https://github.com/user-attachments/assets/17e3d89e-cabd-40c1-9d47-04402e3c734c)
working thanks you
