### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by EthanMG228** [CCobaltDev/SScript-Archive#13]
Soooo i was compiling psych 1.0 prerelease for android and when i installed all it says this:
[30;41m ERROR [0m C:/HaxeToolkit/haxe/lib/SScript/19,0,618/src/macro/Macro.hx:10: characters 96-100

 10 | [2m  Context.fatalError('SScript is not available, thanks to everyone for their support.', (macro [0m[1mnull[0m[2m).pos);[0m
    |                                                                                                [31m^^^^[0m
    | SScript is not available, thanks to everyone for their support.
    
i tried to install different versions but still. why?

**Comment by tposejank** [comment]
Read the installation instructions. Did you use `haxelib install SScript`? If you did, make sure you follow the instructions in this repository's README.md

**Comment by CCobaltDev** [comment]
1. what in the FUCK happened to that text
2. did you follow the installation instructions? if so, run `haxelib set SScript VERSION` with `VERSION `being the one you downloaded

**Comment by tposejank** [comment]
> 1. what in the FUCK happened to that text

This user most likely is in CMD where ANSI colors dont show up properly

**Comment by EthanMG228** [comment]
> 2. did you follow the installation instructions? if so, run `haxelib set SScript VERSION` with `VERSION `being the one you downloaded
i made that 100000 times but still this

**Comment by tposejank** [comment]
https://github.com/CobaltBar/SScript-Archive?tab=readme-ov-file#for-manual-instructions

**Comment by EthanMG228** [comment]
the problem is fixed but it shows an another error:
`[30;41m ERROR [0m source/mobile/backend/StorageUtil.hx:94: characters 23-40

  94 | [2m   AndroidPermissions.[0m[1mrequestPermission[0m[2m('READ_EXTERNAL_STORAGE');[0m
     |                       [31m^^^^^^^^^^^^^^^^^[0m
     | Class<android.Permissions> has no field requestPermission (Suggestion: requestPermissions)

     [30;41m -> [0m export/release/android/haxe/ApplicationMain.hx:153: characters 5-36

      153 | [2m    [0m[1mApplicationMain.getEntryPoint()[0m[2m;[0m
          |     [31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
          | Called from macro here

[30;41m ERROR [0m source/mobile/backend/StorageUtil.hx:95: characters 23-40

  95 | [2m   AndroidPermissions.[0m[1mrequestPermission[0m[2m('WRITE_EXTERNAL_STORAGE');[0m
     |                       [31m^^^^^^^^^^^^^^^^^[0m
     | Class<android.Permissions> has no field requestPermission (Suggestion: requestPermissions)

     [30;41m -> [0m export/release/android/haxe/ApplicationMain.hx:153: characters 5-36

      153 | [2m    [0m[1mApplicationMain.getEntryPoint()[0m[2m;[0m
          |     [31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
          | Called from macro here

[30;41m ERROR [0m source/backend/SpectralAnalyzerEx.hx:111: characters 6-13

 111 | [2m var [0m[1m_buffer[0m[2m:Array<Float> = [];[0m
     |      [31m^^^^^^^[0m
     | Redefinition of variable _buffer in subclass is not allowed. Previously declared at funkin.vis.dsp.SpectralAnalyzer`
i'm gonna ask in the mobile porting discord tf is this

**Comment by EthanMG228** [comment]
i'm gonna open that until it get compiled

**Comment by tposejank** [comment]
There are no Sscript issues here; this isn't our responsibility anymore. Tip: Downgrade your `extension-androidtools`

**Comment by EthanMG228** [comment]
okay
